/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HazelnutChocolateRouteImport } from './routes/hazelnut-chocolate'
import { Route as IndexRouteImport } from './routes/index'

const HazelnutChocolateRoute = HazelnutChocolateRouteImport.update({
  id: '/hazelnut-chocolate',
  path: '/hazelnut-chocolate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hazelnut-chocolate': typeof HazelnutChocolateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hazelnut-chocolate': typeof HazelnutChocolateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hazelnut-chocolate': typeof HazelnutChocolateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hazelnut-chocolate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hazelnut-chocolate'
  id: '__root__' | '/' | '/hazelnut-chocolate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HazelnutChocolateRoute: typeof HazelnutChocolateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/hazelnut-chocolate': {
      id: '/hazelnut-chocolate'
      path: '/hazelnut-chocolate'
      fullPath: '/hazelnut-chocolate'
      preLoaderRoute: typeof HazelnutChocolateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HazelnutChocolateRoute: HazelnutChocolateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
